// ==================================================
// Core packages
// ==================================================
//import color from "color";

import type { Theme } from "#/types/Styles.ts";

export const LightTheme: Theme = {
  dark: false,
  colors: {
    primary: "#406836",
    surfaceTint: "#406836",
    onPrimary: "#FFFFFF",
    primaryContainer: "#C0EFB0",
    onPrimaryContainer: "#002200",
    secondary: "#54634D",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#D7E8CD",
    onSecondaryContainer: "#121F0E",
    tertiary: "#386568",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#BCEBEE",
    onTertiaryContainer: "#002022",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#410002",
    background: "#F8FBF1",
    onBackground: "#191D17",
    surface: "#F8FBF1",
    onSurface: "#191D17",
    surfaceVariant: "#DFE4D7",
    onSurfaceVariant: "#43483F",
    outline: "#73796E",
    outlineVariant: "#C3C8BC",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#2E322B",
    inverseOnSurface: "#EFF2E8",
    inversePrimary: "#A5D395",
    primaryFixed: "#C0EFB0",
    onPrimaryFixed: "#002200",
    primaryFixedDim: "#A5D395",
    onPrimaryFixedVariant: "#285020",
    secondaryFixed: "#D7E8CD",
    onSecondaryFixed: "#121F0E",
    secondaryFixedDim: "#BBCBB2",
    onSecondaryFixedVariant: "#3C4B37",
    tertiaryFixed: "#BCEBEE",
    onTertiaryFixed: "#002022",
    tertiaryFixedDim: "#A0CFD2",
    onTertiaryFixedVariant: "#1E4D50",
    surfaceDim: "#D8DBD2",
    surfaceBright: "#F8FBF1",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F2F5EB",
    surfaceContainer: "#ECEFE5",
    surfaceContainerHigh: "#E6E9E0",
    surfaceContainerHighest: "#E1E4DA",
  },
};
