// ==================================================
// Core packages
// ==================================================
//import color from "color";

import type { Theme } from "#/types/Styles.ts";

export const LightTheme_high_contrast: Theme = {
  dark: false,
  colors: {
    primary: "#022901",
    surfaceTint: "#406836",
    onPrimary: "#FFFFFF",
    primaryContainer: "#244B1D",
    onPrimaryContainer: "#FFFFFF",
    secondary: "#182614",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#394733",
    onSecondaryContainer: "#FFFFFF",
    tertiary: "#002729",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#19494C",
    onTertiaryContainer: "#FFFFFF",
    error: "#4E0002",
    onError: "#FFFFFF",
    errorContainer: "#8C0009",
    onErrorContainer: "#FFFFFF",
    background: "#F8FBF1",
    onBackground: "#191D17",
    surface: "#F8FBF1",
    onSurface: "#000000",
    surfaceVariant: "#DFE4D7",
    onSurfaceVariant: "#20251D",
    outline: "#3F453B",
    outlineVariant: "#3F453B",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#2E322B",
    inverseOnSurface: "#FFFFFF",
    inversePrimary: "#CAF9B8",
    primaryFixed: "#244B1D",
    onPrimaryFixed: "#FFFFFF",
    primaryFixedDim: "#0D3408",
    onPrimaryFixedVariant: "#FFFFFF",
    secondaryFixed: "#394733",
    onSecondaryFixed: "#FFFFFF",
    secondaryFixedDim: "#23301E",
    onSecondaryFixedVariant: "#FFFFFF",
    tertiaryFixed: "#19494C",
    onTertiaryFixed: "#FFFFFF",
    tertiaryFixedDim: "#003235",
    onTertiaryFixedVariant: "#FFFFFF",
    surfaceDim: "#D8DBD2",
    surfaceBright: "#F8FBF1",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F2F5EB",
    surfaceContainer: "#ECEFE5",
    surfaceContainerHigh: "#E6E9E0",
    surfaceContainerHighest: "#E1E4DA",
  },
};
