// ==================================================
// Core packages
// ==================================================
//import color from "color";

import type { Theme } from "#/types/Styles.ts";

export const LightTheme_medium_contrast: Theme = {
  dark: false,
  colors: {
    primary: "#244B1D",
    surfaceTint: "#406836",
    onPrimary: "#FFFFFF",
    primaryContainer: "#557F4A",
    onPrimaryContainer: "#FFFFFF",
    secondary: "#394733",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#6A7963",
    onSecondaryContainer: "#FFFFFF",
    tertiary: "#19494C",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#4F7C7F",
    onTertiaryContainer: "#FFFFFF",
    error: "#8C0009",
    onError: "#FFFFFF",
    errorContainer: "#DA342E",
    onErrorContainer: "#FFFFFF",
    background: "#F8FBF1",
    onBackground: "#191D17",
    surface: "#F8FBF1",
    onSurface: "#191D17",
    surfaceVariant: "#DFE4D7",
    onSurfaceVariant: "#3F453B",
    outline: "#5B6157",
    outlineVariant: "#777D72",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#2E322B",
    inverseOnSurface: "#EFF2E8",
    inversePrimary: "#A5D395",
    primaryFixed: "#557F4A",
    onPrimaryFixed: "#FFFFFF",
    primaryFixedDim: "#3D6633",
    onPrimaryFixedVariant: "#FFFFFF",
    secondaryFixed: "#6A7963",
    onSecondaryFixed: "#FFFFFF",
    secondaryFixedDim: "#51604B",
    onSecondaryFixedVariant: "#FFFFFF",
    tertiaryFixed: "#4F7C7F",
    onTertiaryFixed: "#FFFFFF",
    tertiaryFixedDim: "#366366",
    onTertiaryFixedVariant: "#FFFFFF",
    surfaceDim: "#D8DBD2",
    surfaceBright: "#F8FBF1",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F2F5EB",
    surfaceContainer: "#ECEFE5",
    surfaceContainerHigh: "#E6E9E0",
    surfaceContainerHighest: "#E1E4DA",
  },
};
